apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minecraft
  name: minecraft
spec:
  restartPolicy: Always
  containers:
    - name: server
      image: docker.io/itzg/minecraft-server:latest
      envFrom:
      - configMapRef:
          name: secrets
      env:
        - name: MAX_MEMORY
          value: "6G"
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.19.2"
        - name: TYPE
          value: "FORGE"
        - name: DIFFICULTY
          value: "hard"
        - name: ALLOW_FLIGHT
          value: "TRUE"
        - name: ALLOW_NETHER
          value: true
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: true
        - name: FORCE_GAMEMODE
          value: false
        - name: GENERATE_STRUCTURES
          value: true
        - name: HARDCORE
          value: false
        - name: SNOOPER_ENABLED
          value: false
        - name: MAX_BUILD_HEIGHT
          value: 300
        - name: SPAWN_ANIMALS
          value: true
        - name: SPAWN_MONSTERS
          value: true
        - name: SPAWN_NPCS
          value: true
        - name: SPAWN_PROTECTION
          value: 0
      ports:
        - containerPort: 25565
          hostPort: 25565
      resources: {}
      securityContext:
        capabilities:
          add:
            - CAP_SYS_NICE
          drop:
            - CAP_MKNOD
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /data
          name: data

  volumes:
    - name: data
      hostPath:
        path: /home/mc/minecraft/data
        type: Directory
